export const shopItemsData = [
  {
    id: "jfhgbvnscs",
    name: "Casual Shirt",
    price: 45,
    desc: "A comfortable and stylish casual shirt perfect for everyday wear.",
    img: "/images/img-1.jpg",
  },
  {
    id: "ioytrhndcv",
    name: "Office Shirt",
    price: 100,
    desc: "A crisp, professional office shirt to keep you looking sharp at work.",
    img: "/images/img-2.jpg",
  },
  {
    id: "wuefbncxbsn",
    name: "T-Shirt",
    price: 25,
    desc: "A classic t-shirt made from premium cotton for maximum comfort.",
    img: "/images/img-3.jpg",
  },
  {
    id: "thyfhcbcv",
    name: "Men's Suit",
    price: 300,
    desc: "An elegant men's suit suitable for formal occasions and business meetings.",
    img: "/images/img-4.jpg",
  },
  {
    id: "thiecbawdjksadjk",
    name: "Men's Tie",
    price: 25,
    desc: "A stylish tie to complement your formal attire and make a statement.",
    img: "/images/img-5.png",
  },
  {
    id: "iuertrywebncdjksadjk",
    name: "Casual Shoes",
    price: 200,
    desc: "Comfortable casual shoes perfect for daily activities and outings.",
    img: "/images/img-6.png",
  },
  {
    id: "thierytbvcbvzdhadjk",
    name: "Black Suit",
    price: 450,
    desc: "A classic black suit for timeless elegance at any formal event.",
    img: "/images/img-7.png",
  },
  {
    id: "trfoiwfcnbcawdjksadjk",
    name: "Polo Shirt",
    price: 45,
    desc: "A stylish polo shirt suitable for both casual and semi-formal occasions.",
    img: "/images/img-8.png",
  },
  {
    id: "cbvxbcvsceldk",
    name: "Denim Shirt",
    price: 85,
    desc: "A rugged denim shirt for a casual yet fashionable look.",
    img: "/images/img-9.png",
  },
  {
    id: "oiopijmjkhuihb",
    name: "Denim Pants",
    price: 120,
    desc: "Classic denim pants that are both comfortable and durable.",
    img: "/images/img-10.png",
  },
  {
    id: "oiopijewyiohbjhib",
    name: "Basic Cap",
    price: 35,
    desc: "A basic cap to complete your casual ensemble and protect you from the sun.",
    img: "/images/img-11.png",
  },
  {
    id: "rtytytuyuytyytbvncv",
    name: "Leather Boots",
    price: 350,
    desc: "Premium leather boots for a rugged yet refined look.",
    img: "/images/img-12.png",
  },
];
